"use client";

import { useEffect, useMemo, useState } from "react";
import {
  Badge,
  Box,
  Button,
  HStack,
  Text,
  VStack,
} from "@chakra-ui/react";
import AlgorithmDialogButton, {
  darkSecondaryButtonProps,
} from "@/components/Animations/AlgorithmDialogButton";

type Triangle = {
  a: [number, number];
  b: [number, number];
  c: [number, number];
  depth: number;
};

const TRIANGLE_DEPTH = 7;
const CYCLE_SECONDS = 7;
const SQRT3 = Math.sqrt(3);

const SIERPINSKI_ALGO = {
  title: "Sierpinski triangle recursion",
  summary:
    "The triangle is generated by recursively splitting one triangle into three corner triangles and removing the center. The animation keeps zooming into one corner to show the same rule repeating at every scale.",
  steps: [
    "Start with one equilateral triangle.",
    "Find the midpoint of each edge.",
    "Recurse into the three corner triangles.",
    "Render only the smallest triangles at the chosen depth.",
    "Continuously zoom into the same corner to make self-similarity obvious.",
  ],
  code: `const ab = midpoint(a, b);
const ac = midpoint(a, c);
const bc = midpoint(b, c);

collectTriangles(a, ab, ac, depth - 1, triangles);
collectTriangles(ab, b, bc, depth - 1, triangles);
collectTriangles(ac, bc, c, depth - 1, triangles);`,
  note:
    "This is a pure recursion demo: the rendering is just the final collection of surviving triangles.",
};

const midpoint = (p1: [number, number], p2: [number, number]): [number, number] => {
  return [(p1[0] + p2[0]) / 2, (p1[1] + p2[1]) / 2];
};

const collectTriangles = (
  a: [number, number],
  b: [number, number],
  c: [number, number],
  depth: number,
  triangles: Triangle[] = [],
) => {
  if (depth === 0) {
    triangles.push({ a, b, c, depth });
    return triangles;
  }

  const ab = midpoint(a, b);
  const ac = midpoint(a, c);
  const bc = midpoint(b, c);

  collectTriangles(a, ab, ac, depth - 1, triangles);
  collectTriangles(ab, b, bc, depth - 1, triangles);
  collectTriangles(ac, bc, c, depth - 1, triangles);

  return triangles;
};

const SierpinskiTriangleZoom = () => {
  const [playing, setPlaying] = useState(true);
  const [elapsed, setElapsed] = useState(0);

  useEffect(() => {
    if (!playing) {
      return;
    }

    let frameId = 0;
    let start = 0;

    const loop = (now: number) => {
      if (!start) {
        start = now;
      }

      setElapsed((now - start) / 1000);
      frameId = window.requestAnimationFrame(loop);
    };

    frameId = window.requestAnimationFrame(loop);

    return () => {
      window.cancelAnimationFrame(frameId);
    };
  }, [playing]);

  const triangles = useMemo(() => {
    return collectTriangles([0, 0], [-1, SQRT3], [1, SQRT3], TRIANGLE_DEPTH);
  }, []);

  const cycle = elapsed / CYCLE_SECONDS;
  const cycleIndex = Math.floor(cycle);
  const phase = cycle - cycleIndex;
  const zoom = Math.pow(2, phase);
  const pulse = 0.05 + Math.sin(elapsed * 1.6) * 0.015;

  const strokeOpacity = 0.12 + phase * 0.2;

  return (
    <VStack align="stretch" spacing={6}>
      <Box>
        <Badge colorScheme="purple" mb={3}>
          Fractal zoom
        </Badge>
        <HStack justify="space-between" align="start" gap={4} wrap="wrap">
          <Box>
            <Text fontSize="3xl" fontWeight="bold" lineHeight="1.1" mb={2}>
              Sierpinski Triangle Zoom
            </Text>
            <Text color="gray.600" maxW="3xl">
              The scene keeps zooming into the same self-similar corner, so the
              triangle appears to continue forever.
            </Text>
          </Box>

          <HStack spacing={3}>
            <Badge colorScheme="orange" px={3} py={1} borderRadius="full">
              Zoom x{zoom.toFixed(2)}
            </Badge>
            <Badge colorScheme="gray" px={3} py={1} borderRadius="full">
              Depth {TRIANGLE_DEPTH}
            </Badge>
            <Badge colorScheme="teal" px={3} py={1} borderRadius="full">
              Cycle {cycleIndex + 1}
            </Badge>
          </HStack>
        </HStack>
      </Box>

      <HStack wrap="wrap">
        <Button
          colorScheme="orange"
          onClick={() => setPlaying((value) => !value)}
        >
          {playing ? "Pause" : "Resume"}
        </Button>
        <Button
          onClick={() => {
            setElapsed(0);
            setPlaying(true);
          }}
          {...darkSecondaryButtonProps}
        >
          Restart
        </Button>
        <AlgorithmDialogButton
          title={SIERPINSKI_ALGO.title}
          summary={SIERPINSKI_ALGO.summary}
          steps={SIERPINSKI_ALGO.steps}
          code={SIERPINSKI_ALGO.code}
          note={SIERPINSKI_ALGO.note}
        />
      </HStack>

      <Box
        overflow="hidden"
        borderRadius="3xl"
        borderWidth="1px"
        borderColor="blackAlpha.100"
        bg="linear-gradient(180deg, #10172a 0%, #040816 100%)"
        boxShadow="0 32px 80px rgba(15, 23, 42, 0.28)"
      >
        <Box
          position="relative"
          minH={{ base: "520px", lg: "680px" }}
          p={{ base: 4, md: 8 }}
        >
          <Box
            position="absolute"
            inset={0}
            backgroundImage="
              radial-gradient(circle at top, rgba(251, 146, 60, 0.16), transparent 35%),
              radial-gradient(circle at 20% 20%, rgba(56, 189, 248, 0.12), transparent 26%),
              radial-gradient(circle at 80% 30%, rgba(168, 85, 247, 0.10), transparent 24%)
            "
          />

          <Box
            position="relative"
            h="100%"
            display="flex"
            alignItems="center"
            justifyContent="center"
            transform={`scale(${zoom}) translateY(${pulse}rem)`}
            transformOrigin="50% 12%"
            transition="transform 40ms linear"
          >
            <svg
              viewBox="-1.1 -0.12 2.2 1.98"
              width="100%"
              style={{
                maxWidth: "960px",
                display: "block",
                overflow: "visible",
              }}
            >
              <defs>
                <linearGradient id="sierpinski-fill" x1="0%" y1="0%" x2="100%" y2="100%">
                  <stop offset="0%" stopColor="#fde68a" stopOpacity="0.95" />
                  <stop offset="45%" stopColor="#fb923c" stopOpacity="0.9" />
                  <stop offset="100%" stopColor="#7c3aed" stopOpacity="0.88" />
                </linearGradient>
              </defs>

              <g>
                {triangles.map((triangle, index) => {
                  const opacity = 0.45 + (triangle.depth / TRIANGLE_DEPTH) * 0.4;
                  const fill = index % 5 === 0 ? "url(#sierpinski-fill)" : "#ffffff";
                  const points = `${triangle.a.join(",")} ${triangle.b.join(",")} ${triangle.c.join(",")}`;

                  return (
                    <polygon
                      key={`${triangle.a.join("-")}-${triangle.b.join("-")}-${triangle.c.join("-")}`}
                      points={points}
                      fill={fill}
                      fillOpacity={fill === "#ffffff" ? opacity * 0.12 : opacity}
                      stroke="#f8fafc"
                      strokeOpacity={strokeOpacity}
                      strokeWidth="0.01"
                    />
                  );
                })}
              </g>

              <polygon
                points="0,0 -1,1.732 1,1.732"
                fill="none"
                stroke="#fef3c7"
                strokeOpacity="0.8"
                strokeWidth="0.03"
              />
            </svg>
          </Box>
        </Box>
      </Box>
    </VStack>
  );
};

export default SierpinskiTriangleZoom;
