[alembic]
# folder that contains env.py and versions/
script_location = alembic

# allows "app." imports to work
prepend_sys_path = .

# timezone support (optional but recommended)
timezone = UTC

# we DO NOT set sqlalchemy.url here
# it is injected from env.py using DATABASE_URL_SYNC


[loggers]
keys = root,sqlalchemy,alembic


[handlers]
keys = console


[formatters]
keys = generic


[logger_root]
level = WARN
handlers = console


[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine


[logger_alembic]
level = INFO
handlers =
qualname = alembic


[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic


[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S