"use client";

import React, { useEffect, useMemo, useRef, useState } from "react";
import { Canvas, useFrame } from "@react-three/fiber";
import { Line, OrbitControls } from "@react-three/drei";
import * as THREE from "three";
import {
  Box,
  Button,
  HStack,
  Slider,
  SliderFilledTrack,
  SliderThumb,
  SliderTrack,
  Stat,
  StatLabel,
  StatNumber,
  Text,
  VStack,
} from "@chakra-ui/react";
import AlgorithmDialogButton, {
  darkSecondaryButtonProps,
} from "@/components/Animations/AlgorithmDialogButton";

type HilbertSceneProps = {
  points: THREE.Vector3[];
  visibleCount: number;
  autoRotate: boolean;
  showNodes: boolean;
};

const toFixed = (value: number, digits = 2) => {
  return Number.isFinite(value) ? value.toFixed(digits) : "NaN";
};

const HILBERT_ALGO = {
  title: "Hilbert curve recursion",
  summary:
    "The 3D Hilbert curve is generated by a recursive octant walk. Each step rewrites the path into eight half-size subpaths, with rotations chosen so the traversal stays continuous and local.",
  steps: [
    "Pick an order and start with one cube.",
    "Split the cube into 8 octants and recurse into each octant in a specific orientation.",
    "Rotate the local frame before entering each child so the path exits one octant directly into the next.",
    "Collect the visited corner points and draw the prefix of the path over time.",
    "Animate the head point to reveal the walk order and locality preservation.",
  ],
  code: `const hilbert3D = (center, size, iterations, v0, v1, v2, v3, v4, v5, v6, v7) => {
  const half = size / 2;
  const corners = [...];
  const vec = [corners[v0], corners[v1], corners[v2], corners[v3], corners[v4], corners[v5], corners[v6], corners[v7]];

  if (--iterations >= 0) {
    return [].concat(
      hilbert3D(vec[0], half, iterations, ...),
      hilbert3D(vec[1], half, iterations, ...),
      hilbert3D(vec[2], half, iterations, ...),
      hilbert3D(vec[3], half, iterations, ...),
      hilbert3D(vec[4], half, iterations, ...),
      hilbert3D(vec[5], half, iterations, ...),
      hilbert3D(vec[6], half, iterations, ...),
      hilbert3D(vec[7], half, iterations, ...),
    );
  }

  return vec;
};`,
  note:
    "At order n, the path visits 8^n cells, but every step is still local to the current octant.",
};

const hilbert3D = (
  center = new THREE.Vector3(0, 0, 0),
  size = 10,
  iterations = 1,
  v0 = 0,
  v1 = 1,
  v2 = 2,
  v3 = 3,
  v4 = 4,
  v5 = 5,
  v6 = 6,
  v7 = 7,
): THREE.Vector3[] => {
  const half = size / 2;

  const corners = [
    new THREE.Vector3(center.x - half, center.y + half, center.z - half),
    new THREE.Vector3(center.x - half, center.y + half, center.z + half),
    new THREE.Vector3(center.x - half, center.y - half, center.z + half),
    new THREE.Vector3(center.x - half, center.y - half, center.z - half),
    new THREE.Vector3(center.x + half, center.y - half, center.z - half),
    new THREE.Vector3(center.x + half, center.y - half, center.z + half),
    new THREE.Vector3(center.x + half, center.y + half, center.z + half),
    new THREE.Vector3(center.x + half, center.y + half, center.z - half),
  ];

  const vec = [
    corners[v0],
    corners[v1],
    corners[v2],
    corners[v3],
    corners[v4],
    corners[v5],
    corners[v6],
    corners[v7],
  ];

  if (--iterations >= 0) {
    let tmp: THREE.Vector3[] = [];

    tmp = tmp.concat(
      hilbert3D(vec[0], half, iterations, v0, v3, v4, v7, v6, v5, v2, v1),
      hilbert3D(vec[1], half, iterations, v0, v7, v6, v1, v2, v5, v4, v3),
      hilbert3D(vec[2], half, iterations, v0, v7, v6, v1, v2, v5, v4, v3),
      hilbert3D(vec[3], half, iterations, v2, v3, v0, v1, v6, v7, v4, v5),
      hilbert3D(vec[4], half, iterations, v2, v3, v0, v1, v6, v7, v4, v5),
      hilbert3D(vec[5], half, iterations, v4, v3, v2, v5, v6, v1, v0, v7),
      hilbert3D(vec[6], half, iterations, v4, v3, v2, v5, v6, v1, v0, v7),
      hilbert3D(vec[7], half, iterations, v6, v5, v2, v1, v0, v3, v4, v7),
    );

    return tmp;
  }

  return vec;
};

const HilbertScene = ({
  points,
  visibleCount,
  autoRotate,
  showNodes,
}: HilbertSceneProps) => {
  const rootRef = useRef<THREE.Group | null>(null);
  const headRef = useRef<THREE.Mesh | null>(null);

  const visiblePoints = useMemo(() => {
    return points.slice(0, Math.max(2, visibleCount));
  }, [points, visibleCount]);

  const headPoint = visiblePoints[visiblePoints.length - 1] ?? new THREE.Vector3();
  const nodePositions = useMemo(() => {
    return points.map((point) => {
      return point.toArray() as [number, number, number];
    });
  }, [points]);

  useFrame((state, delta) => {
    if (rootRef.current && autoRotate) {
      rootRef.current.rotation.y += delta * 0.32;
      rootRef.current.rotation.x = Math.sin(state.clock.elapsedTime * 0.25) * 0.2;
    }

    if (headRef.current) {
      const scale = 1 + Math.sin(state.clock.elapsedTime * 4) * 0.18;
      headRef.current.scale.setScalar(scale);
    }
  });

  return (
    <>
      <color attach="background" args={["#020617"]} />
      <fog attach="fog" args={["#020617", 18, 44]} />
      <ambientLight intensity={0.65} />
      <directionalLight position={[8, 12, 10]} intensity={1.15} />
      <pointLight position={[-8, -6, 10]} intensity={0.7} color="#67e8f9" />
      <OrbitControls makeDefault />

      <group ref={rootRef}>
        <mesh>
          <boxGeometry args={[12.5, 12.5, 12.5]} />
          <meshBasicMaterial color="#1e293b" wireframe transparent opacity={0.22} />
        </mesh>

        <Line
          points={nodePositions}
          color="#0f172a"
          lineWidth={1}
          transparent
          opacity={0.55}
        />

        <Line points={visiblePoints} color="#67e8f9" lineWidth={2.5} />

        {showNodes
          ? nodePositions.map((position, index) => {
              const normalized = index / Math.max(1, nodePositions.length - 1);
              const color = new THREE.Color().setHSL(0.38 + normalized * 0.18, 0.85, 0.58);

              return (
                <mesh key={`${position.join("-")}-${index}`} position={position}>
                  <sphereGeometry args={[0.08, 12, 12]} />
                  <meshStandardMaterial
                    color={color}
                    emissive={color}
                    emissiveIntensity={0.45}
                  />
                </mesh>
              );
            })
          : null}

        <mesh ref={headRef} position={headPoint.toArray()}>
          <sphereGeometry args={[0.22, 18, 18]} />
          <meshStandardMaterial color="#f8fafc" emissive="#67e8f9" emissiveIntensity={1.3} />
        </mesh>
      </group>

      <axesHelper args={[8]} />
    </>
  );
};

const HilbertCurve3D = () => {
  const [order, setOrder] = useState(2);
  const [speed, setSpeed] = useState(2.2);
  const [playing, setPlaying] = useState(true);
  const [autoRotate, setAutoRotate] = useState(true);
  const [showNodes, setShowNodes] = useState(false);
  const [visibleCount, setVisibleCount] = useState(2);

  const points = useMemo(() => {
    return hilbert3D(new THREE.Vector3(0, 0, 0), 10, order);
  }, [order]);

  useEffect(() => {
    setVisibleCount(2);
  }, [order]);

  useEffect(() => {
    if (!playing) {
      return;
    }

    const interval = window.setInterval(() => {
      setVisibleCount((current) => {
        if (current >= points.length) {
          return 2;
        }

        return Math.min(points.length, current + Math.max(1, Math.round(speed)));
      });
    }, 32);

    return () => {
      window.clearInterval(interval);
    };
  }, [playing, points.length, speed]);

  const progress = useMemo(() => {
    return Math.min(100, (visibleCount / Math.max(1, points.length)) * 100);
  }, [points.length, visibleCount]);

  const segmentCount = Math.max(0, points.length - 1);
  const occupiedFraction = useMemo(() => {
    return 1 / Math.pow(8, order);
  }, [order]);

  return (
    <HStack align="stretch" spacing={0} w="100%" h="100vh" bg="#020617">
      <Box
        w={{ base: "360px", xl: "420px" }}
        bg="gray.950"
        color="white"
        borderRightWidth="1px"
        borderRightColor="whiteAlpha.200"
        p={4}
      >
        <VStack align="stretch" spacing={5}>
          <Box>
            <Text fontSize="lg" fontWeight="bold">
              Hilbert Space-Filling Curve (3D)
            </Text>
            <Text fontSize="sm" color="whiteAlpha.800">
              A recursive path that visits every octant of a cube while preserving locality.
              This view animates the traversal order in three dimensions.
            </Text>
          </Box>

          <VStack align="stretch" spacing={3}>
            <Box>
              <Text fontSize="sm" mb={2}>
                Iteration order
              </Text>
              <Slider min={1} max={3} step={1} value={order} onChange={setOrder}>
                <SliderTrack>
                  <SliderFilledTrack />
                </SliderTrack>
                <SliderThumb />
              </Slider>
              <Text fontSize="sm" color="whiteAlpha.700" mt={1}>
                Order {order}
              </Text>
            </Box>

            <Box>
              <Text fontSize="sm" mb={2}>
                Draw speed
              </Text>
              <Slider min={1} max={10} step={1} value={speed} onChange={setSpeed}>
                <SliderTrack>
                  <SliderFilledTrack />
                </SliderTrack>
                <SliderThumb />
              </Slider>
              <Text fontSize="sm" color="whiteAlpha.700" mt={1}>
                {speed.toFixed(0)} points / tick
              </Text>
            </Box>
          </VStack>

          <HStack flexWrap="wrap" spacing={3}>
            <Button
              onClick={() => {
                setPlaying((value) => !value);
              }}
              colorScheme={playing ? "orange" : "green"}
            >
              {playing ? "Pause" : "Play"}
            </Button>
            <Button
              onClick={() => {
                setVisibleCount(2);
              }}
              {...darkSecondaryButtonProps}
            >
              Reset Trace
            </Button>
            <AlgorithmDialogButton
              title={HILBERT_ALGO.title}
              summary={HILBERT_ALGO.summary}
              steps={HILBERT_ALGO.steps}
              code={HILBERT_ALGO.code}
              note={HILBERT_ALGO.note}
            />
          </HStack>

          <HStack flexWrap="wrap" spacing={3}>
            <Button
              onClick={() => {
                setAutoRotate((value) => !value);
              }}
              variant={autoRotate ? "solid" : "outline"}
            >
              {autoRotate ? "Auto-Rotate On" : "Auto-Rotate Off"}
            </Button>
            <Button
              onClick={() => {
                setShowNodes((value) => !value);
              }}
              variant={showNodes ? "solid" : "outline"}
            >
              {showNodes ? "Hide Nodes" : "Show Nodes"}
            </Button>
          </HStack>

          <Box
            p={4}
            borderRadius="xl"
            bgGradient="linear(to-br, cyan.500, blue.700)"
            color="white"
          >
            <Text fontSize="sm" fontWeight="600" mb={1}>
              Progress
            </Text>
            <Text fontSize="2xl" fontWeight="bold">
              {toFixed(progress, 1)}%
            </Text>
            <Text fontSize="sm" color="whiteAlpha.900">
              {visibleCount} / {points.length} sampled points drawn
            </Text>
          </Box>

          <HStack spacing={4} align="stretch">
            <Stat
              p={3}
              bg="whiteAlpha.100"
              borderRadius="xl"
              borderWidth="1px"
              borderColor="whiteAlpha.200"
            >
              <StatLabel color="whiteAlpha.700">Points</StatLabel>
              <StatNumber>{points.length}</StatNumber>
            </Stat>
            <Stat
              p={3}
              bg="whiteAlpha.100"
              borderRadius="xl"
              borderWidth="1px"
              borderColor="whiteAlpha.200"
            >
              <StatLabel color="whiteAlpha.700">Segments</StatLabel>
              <StatNumber>{segmentCount}</StatNumber>
            </Stat>
          </HStack>

          <Box
            p={4}
            borderRadius="xl"
            bg="whiteAlpha.100"
            borderWidth="1px"
            borderColor="whiteAlpha.200"
          >
            <Text fontWeight="600" mb={2}>
              Geometry notes
            </Text>
            <Text fontSize="sm" color="whiteAlpha.800">
              Each recursive step replaces one cube visit with eight smaller cube visits.
              At order {order}, the curve occupies sub-cubes of side length{" "}
              {toFixed(occupiedFraction, 4)} of the original edge.
            </Text>
          </Box>
        </VStack>
      </Box>

      <Box flex="1" position="relative">
        <Canvas camera={{ position: [16, 14, 16], fov: 48 }}>
          <HilbertScene
            points={points}
            visibleCount={visibleCount}
            autoRotate={autoRotate}
            showNodes={showNodes}
          />
        </Canvas>
      </Box>
    </HStack>
  );
};

export default HilbertCurve3D;
